//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelingExam.Infrastructure.Repository.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        public string id { get; set; }
        public Nullable<decimal> amountTInsured { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> inceptionDate { get; set; }
        public string installmentPayment { get; set; }
        public string clientId { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
